name: Deploy to Alibaba OSS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Baixar e configurar ossutil
        run: |
          curl -O https://gosspublic.alicdn.com/ossutil/1.7.16/ossutil64
          chmod +x ossutil64
          ./ossutil64 config \
            -e ${{ secrets.OSS_ENDPOINT }} \
            -i ${{ secrets.OSS_KEY_ID }} \
            -k ${{ secrets.OSS_KEY_SECRET }}

      - name: Fazer upload para OSS
        run: |
          ./ossutil64 cp -r dist/ oss://${{ secrets.OSS_BUCKET }}/ --force